name: ansible-lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint on PR
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Add ansible.cfg from secrets
        run: |
          echo -n ${ANSIBLE_CFG} | base64 --decode > ansible.cfg
        shell: bash
        env:
          ANSIBLE_CFG: "${{ secrets.ANSIBLE_CFG }}"

      - name: Install galaxy colletions
        run: ansible-galaxy install -vvvv -r requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

